name: Console Log Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-console-logs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for console logging statements
        run: |
          chmod +x ./scripts/check-console-logs.sh
          ./scripts/check-console-logs.sh 