name: Process Env Usage Check

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-process-env:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check process.env usage
        run: |
          chmod +x ./scripts/check-process-env.sh
          ./scripts/check-process-env.sh 